---
driver:
  name: vagrant
driver_config:
  # we want to explicitly set the chef version
  require_chef_omnibus: 12.4.1

provisioner:
  # chef zero is an in memory feature complete chef server, its preferred by many over chef solo in testing
  name: chef_zero

platforms:
  # 14.04 is the latest LTS
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[hello-world::default]
      - recipe[hello-world::nginx]

  - name: node-1
    run_list:
      - recipe[apt]
      - recipe[hello-world::default]
    driver:
      network:
        - ["private_network", {ip: "10.10.0.11"}]

  - name: node-2
    run_list:
      - recipe[apt]
      - recipe[hello-world::default]
    driver:
      network:
        - ["private_network", {ip: "10.10.0.12"}]

  - name: lb-1
    run_list:
      - recipe[apt]
      - recipe[hello-world::nginx]
    driver:
      network:
        - ["private_network", {ip: "10.10.0.13"}]
    attributes:
      hello-world:
        nginx:
          backends:
            - 10.10.0.11
            - 10.10.0.12
